// <auto-generated />
using System;
using InboxNet.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InboxNet.LoadTests.Migrations
{
    [DbContext(typeof(InboxDbContext))]
    [Migration("20260425062300_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inbox")
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InboxNet.Models.InboxHandlerAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<long>("DurationMs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("HandlerName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("InboxMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("AttemptedAt")
                        .HasDatabaseName("IX_InboxHandlerAttempts_AttemptedAt");

                    b.HasIndex("HandlerName", "AttemptedAt")
                        .HasDatabaseName("IX_InboxHandlerAttempts_HandlerName_AttemptedAt");

                    b.HasIndex("InboxMessageId", "HandlerName")
                        .HasDatabaseName("IX_InboxHandlerAttempts_MessageId_HandlerName");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("InboxMessageId", "HandlerName"), new[] { "Status" });

                    b.ToTable("InboxHandlerAttempts", "inbox");
                });

            modelBuilder.Entity("InboxNet.Models.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("ContentSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DedupKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("ProviderEventId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TraceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("ProviderKey", "DedupKey")
                        .IsUnique()
                        .HasDatabaseName("UX_InboxMessages_ProviderKey_DedupKey");

                    b.HasIndex("ProviderKey", "EventType")
                        .HasDatabaseName("IX_InboxMessages_ProviderKey_EventType");

                    b.HasIndex("Status", "LockedUntil")
                        .HasDatabaseName("IX_InboxMessages_Status_LockedUntil")
                        .HasFilter("[LockedUntil] IS NOT NULL");

                    b.HasIndex("Status", "ReceivedAt", "LockedUntil", "NextRetryAt")
                        .HasDatabaseName("IX_InboxMessages_Lock_Candidate")
                        .HasFilter("[Status] IN (0, 1)");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Status", "ReceivedAt", "LockedUntil", "NextRetryAt"), new[] { "TenantId", "ProviderKey", "EntityId", "EventType", "RetryCount" });

                    b.HasIndex("TenantId", "ProviderKey", "EntityId", "Status", "LockedUntil")
                        .HasDatabaseName("IX_InboxMessages_PartitionKey_Status");

                    b.ToTable("InboxMessages", "inbox");
                });

            modelBuilder.Entity("InboxNet.Models.InboxHandlerAttempt", b =>
                {
                    b.HasOne("InboxNet.Models.InboxMessage", "InboxMessage")
                        .WithMany()
                        .HasForeignKey("InboxMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InboxMessage");
                });
#pragma warning restore 612, 618
        }
    }
}
